#server:
#  port: 8301
#spring:
#  application:
#    name: ribbon-service
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#
## 自定user-service调用路径
#service:
#  url:
#    user: http://user-service
#
## Ribbon的常用配置
#ribbon:
#  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
#  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
#  OkToRetryOnAllOperations: true #对超时请求启用重试机制
#  MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
#  MaxAutoRetries: 1 # 切换实例后重试最大次数
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改负载均衡算法
#
